[general]
import = ["~/.config/alacritty/themes/themes/tokyo_night.toml"]

[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
bold = { family = "RobotoMono Nerd Font", style = "Bold" }
italic = { family = "RobotoMono Nerd Font", style = "Italic" }
bold_italic = { family = "RobotoMono Nerd Font", style = "Bold Italic" }
size = 12.0


[window]
opacity = 0.97

[selection]
save_to_clipboard = true
